version: "3.8"
 
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nithish123
      POSTGRES_DB: consultancy
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
 
  api:
    image: consultancymanagement  
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=nithish123;Host=db;Port=5432;Database=consultancy;   
    ports:
      - "5001:8080"
      - "5002:8081"
    depends_on:
      - db
 
volumes:
  pgdata: